name: test-gha
on:
  workflow_dispatch:
jobs:
  # terraform_install:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v7.0.0
  #     - name: HashiCorp - Setup Terraform  
  #       uses: hashicorp/setup-terraform@v4
  azure_login:
     name: azure login job
     runs-on: ubuntu-latest
     steps:
       - name: login via hardcoded secrets
         uses: azure/login@v3
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      
      
      
